### ISSUE TITLE
How do I change host?

### ISSUE THREAD

**Issue by zhulik** [socketry/protocol-http1#16]
Hello,

I'm trying to connect to a websocket endpoint located in an AWS private network via an ssh tunnel on an EC2 instance. I use localhost in the url, but I'd like the real hostname of the endpoint to be sent to server. 

From what I see in https://github.com/socketry/protocol-http1/blob/main/lib/protocol/http1/connection.rb#L122, the client strictly sends the authority even if headers have `host` overridden.

I my case a real host value must be passed to the server in order to pass the sigv4 verification.

Is there a workaround to send right host to the server without modifying /etc/hosts ?

Thanks!

**Comment by zhulik** [comment]
I tested everything locally with changed in my PR, everything works now

**Comment by ioquatix** [comment]
The `host` header is HTTP/1 specific, we need a solution which works in a generic way. You can just specify the correct host header in the `Async::HTTP::Endpoint` but connect to localhost for the actual connection.

```ruby
Async::HTTP::Endpoint.parse("http://private-host", Async::IO::Endpoint.tcp("localhost", ...))
```
