### ISSUE TITLE
TypeError starting in 7330bc68

### ISSUE THREAD

**Issue by trevorturk** [socketry/protocol-http1#37]
Starting with 7330bc68, I'm getting `TypeError (can't convert nil into Integer)` in `lib/protocol/http1/connection.rb:214` in `read_response_line` (`status = Integer(status)`) for some (not all) URLs. An example URL that fails is: `https://dataservice.accuweather.com/currentconditions/v1/2626585?apikey=xxx` -- I'm sorry, I'm not sure what exactly is going wrong, but pinning to the commit before `7330bc68` fixes the issue, so I hope that might be a hint. Please let me know if I can help debug in any other way, though!

**Comment by ioquatix** [comment]
Sorry about this, there are some internal churn in `protocol-http` and `async-http` which is taking longer than expected to work through. There are a few rough edges in the last release.

**Comment by trevorturk** [comment]
No worries, I'll keep an eye out for changes and can test and report back!

**Comment by trevorturk** [comment]
I've been doing a quick test every few days as I see updates, and this combo seems to solve this problem.

```
protocol-http (0.37.0)
protocol-http1 (0.25.0)
```

So, I think it's safe to close this, but please do let me know what you think!

**Comment by ioquatix** [comment]
Thanks for following up on this issue and your continued support & testing!
