### ISSUE TITLE
Tests failure on armhf

### ISSUE THREAD

**Issue by lucaskanashiro** [socketry/protocol-http1#7]
Two tests fail while trying to run the test suite in Ubuntu armhf (development release):

```
Failures:

  1) Protocol::HTTP1::Body::Fixed#read with large stream allocates expected amount of memory
     Failure/Error:
       expect do
       	subject.read.clear until subject.empty?
       end.to limit_allocations(size: 0)

       exceeded allocation limit: allocated 1 instances, -16 bytes, expected exactly 0 bytes
     # ./spec/protocol/http1/body/fixed_spec.rb:96:in `block (4 levels) in <top (required)>'

  2) Protocol::HTTP1::Body::Remainder#read with large stream allocates expected amount of memory
     Failure/Error:
       expect do
       	subject.read.clear until subject.empty?
       end.to limit_allocations(size: 0)

       exceeded allocation limit: allocated 640 instances, -10240 bytes, expected exactly 0 bytes
     # ./spec/protocol/http1/body/remainder_spec.rb:71:in `block (4 levels) in <top (required)>'

Finished in 0.34216 seconds (files took 0.48831 seconds to load)
57 examples, 2 failures, 1 pending
```

Check the full test log [here](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/armhf/r/ruby-protocol-http1/20200701_211700_9bd7d@/log.gz). They passed in all other architectures (amd64, arm64, ppc64el, and s390x). Checking for memory allocation in a 32 bit platform in the same way you do in a 64 bit one should be the problem here.

**Comment by ioquatix** [comment]
Yeah, I think the problem is Ruby doesn't expose enough details of the underlying size of VALUE. What would be the best way to fix that?

**Comment by ioquatix** [comment]
These specs have been removed, and in addition, the `rspec-memory` gem was updated to mitigate this issue by computing the size of `VALUE` rather than hard coding it.

Thanks for your report.
